### ISSUE TITLE
`ptw`

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/SymmetryBook#105]
Does anyone know what `ptw` is an acronym of?

<img width="639" alt="Screen Shot 2021-05-05 at 4 12 03 PM" src="https://user-images.githubusercontent.com/700228/117209978-b9f17c80-adbc-11eb-96d1-74b79d6bde79.png">

**Comment by bidundas** [comment]
I don’t know, but I can guess at “pointwise”?

Bjorn

**Comment by marcbezem** [comment]
Right, Bjørn!

**Comment by DanGrayson** [comment]
Thanks, I've added that to the footnote:

<img width="899" alt="Screen Shot 2021-05-06 at 8 57 36 AM" src="https://user-images.githubusercontent.com/700228/117310734-2d40d000-ae49-11eb-9e95-4c57fc83ba62.png">
