### ISSUE TITLE
"index type" -- "family indexed by"

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/SymmetryBook#107]
We agreed yesterday that we would change phrases like "a family indexed by a variable x" to "a family parametrized by a variable x".  But now I see that in lots of places where "indexed by" is used, the type is called the "index type", and I also see that when referring to products of the form " \prod _ {x:X} T(x) ", the type X is called the "index type" of the product.  How about if I change those uses also to "parameter type", and add something to the style guide?

**Comment by DanGrayson** [comment]
Oops, never mind, I see from my notes from yesterday that we did agree on that.

**Comment by marcbezem** [comment]
Note that we also have the terminology "base type" X of the type family T. I think we also use that for products and sums.
A reduction from three to two synonyms is fine with me.
