### ISSUE TITLE
semidirect product

### ISSUE THREAD

**Issue by bidundas** [UniMath/SymmetryBook#11]
I am happy about leaving the tilde on top of the H in G\ltimes H.  It conforms with current practice where one remembers the action (often as a subscript on the \ltimes, but why not at the top of H?).

Remember to define the homomorphism H(pt_G)-> G\ltimes\tilde H (and show that it is the kernel)

**Comment by DanGrayson** [comment]
Okay, I'll implement that.

**Comment by DanGrayson** [comment]
Done in commit 93d54b29
