### ISSUE TITLE
Citing the book

### ISSUE THREAD

**Issue by vikraman** [UniMath/SymmetryBook#112]
I would like to cite this book in a paper. What would be the best way to write it in BibTeX? I wrote something similar to the HoTT book but I'm not sure if that's correct.

```
@book{symmetryBook2021,
  title = {Symmetry},
  author = {Univalent Foundations Program, The},
  year = {2021},
  publisher = {{Univalent Foundations Program}},
  url = {https://unimath.github.io/SymmetryBook/book.pdf},
}
```

**Comment by DanGrayson** [comment]
Gee, we haven't even discussed that yet.  We might end up having a list of names for the authors.  In any case, it won't be the Univalent Foundations Program (I think).

**Comment by marcbezem** [comment]
I got another request (by Thierry Coquand) on how to cite the book. I think we have to take a (temporary) decision, and
mention it in README.md. What about:
```
@misc{CitekeyMisc,
      title        = "{Symmetry}",
      howpublished = "\url{https://unimath.github.io/SymmetryBook/}",
      note         = "Accessed: AccessDate"
    }
```

**Comment by DanGrayson** [comment]
The commit number used for access would be better than the date, as there's no way to deduce the commit number from the date.

The URL doesn't work.

**Comment by marcbezem** [comment]
Corrected, thanks!

**Comment by UlrikBuchholtz** [comment]
I've updated the pdf on gh-pages. But maybe the URL will change once issue #119 is closed…

**Comment by UlrikBuchholtz** [comment]
I'm closing since we now have a BibTeX snippet on the copyright page.
