### ISSUE TITLE
being equivalent

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/SymmetryBook#115]
If we speak of two types being equivalent, it sounds like equivalence is a proposition.  We don't do that for equality.  What should we do?

<img width="564" alt="Screen Shot 2021-08-05 at 3 58 15 PM" src="https://user-images.githubusercontent.com/700228/128413348-91fc1838-73ae-4307-af61-d5fcb4fba11f.png">

**Comment by bidundas** [comment]
I'd prefer to avoid 'equivalent' in this sense, and if used it should refer to the propositional truncation of the type of equivalences. 

Bjorn

**Comment by DanGrayson** [comment]
Instead of saying "X and Y are equivalent", we could say "there is an equivalence between X and Y".  (We do the same for identifications.)  That would avoid talking about propositional truncation here.

**Comment by bidundas** [comment]
That would work and treating them in the same fashion seems ideologically sound. 

Bjorn

**Comment by UlrikBuchholtz** [comment]
I agree!

**Comment by DanGrayson** [comment]
Okay, I've eliminated several uses of the word "equivalent", and reworded its introduction.  (I didn't have the energy to remove them all.)
