### ISSUE TITLE
bottom margin

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/SymmetryBook#117]
The bottom margin seems to be too large:

<img width="366" alt="Screen Shot 2021-08-10 at 6 57 19 AM" src="https://user-images.githubusercontent.com/700228/128855382-974b2bc3-b383-4213-907b-d2120ed10227.png">

**Comment by UlrikBuchholtz** [comment]
Not sure why the lower margin was set to 2in. I've now reduced it to 1in (same as the left and top margins) in f23c013. Feel free to reopen if you'd prefer a different value.

**Comment by DanGrayson** [comment]
Thanks, that looks much better.
