### ISSUE TITLE
can we have set coequalizers, please?

### ISSUE THREAD

**Issue by bidundas** [UniMath/SymmetryBook#12]
Request: I need set coequalizer (p88 4.7)

**Comment by DanGrayson** [comment]
This should include quotients of types by equivalence relations, yielding sets.

**Comment by bidundas** [comment]
Btw. the induced torsor is easy to define without set quotients IF you allow me set-truncation (which it seems we are converging towards thinking of as kosher):

if X:BG->Set is a G-set and f:Hom(G,H), then f_*X:BH->Set is given by

f_*X(y) = ||\sum_{x:BG} (y=Bf(x)) x X(x)||_0

which is a torsor if X is.

What do you prefer?  Another example where it would have been more convenient to go with \infty-groups.

**Comment by UlrikBuchholtz** [comment]
I think it's useful to eventually combine the two perspectives. In commit fee0fa7 I added a new section (5.8) that shows that orbit types are groupoid completions, and thus orbit sets are set quotients. The latter could of course be done directly, but perhaps not as elegantly. (As @bidundas says, infty-groups are convenient.)

(Of course I'm all for having both set quotients and set truncations in our type theory.)

**Comment by DanGrayson** [comment]
That's a cool definition, too.  I don't see any reason to shun set-quotients, though.

**Comment by bidundas** [comment]
Very good (though "pregroupoid" hasn’t yet been defined).  Your addition conforms with how I was thinking. 

Bjorn

**Comment by coquand** [comment]
Really nice to have such definitions without set quotients at the level of G-sets!

 I also found the formulation of Deligne in the paper of tamed symbols short and elegant
(but it works only at the level of torsors): if X is a G-torsor and f : G -> H then we look
for pairs Y, f   Y H-torsor
with f:X -> Y such that f( x.g) = f(x). f(g) for x in X and g in G and f_*X, f  
is defined as the unique solution (up to isomorphism in Deligne’s paper) of this problem.
