### ISSUE TITLE
Copyright page

### ISSUE THREAD

**Issue by UlrikBuchholtz** [UniMath/SymmetryBook#120]
We should have a copyright page on p. 2. Here we can also add a copyable BibTeX snippet at the bottom as suggested in issue #112.

One question (also related to #112) is the copyright author: We can either make a new entity (something like “The Symmetry Book Authors”), or we could just have a list of names. What do you think?

**Comment by bidundas** [comment]
I think the young guys for whom this might make a difference should decide.

Bjorn

**Comment by UlrikBuchholtz** [comment]
In that case, I think we should just list our names, which I've done in 7e714ef – we can add names later if necessary. We should probably also add some further names to the acknowledgements.

I also added a BibTeX snippet. When you copy from the PDF, the spaces/linebreaks are not preserved (at least with qpdfview), but running it though `bibtool` recovers the layout.

Everyone happy with the copyright page?

**Comment by DanGrayson** [comment]
It looks good, thank you.
