### ISSUE TITLE
 "Clesch and Jordan" -> "Clebsch and Gordan"

### ISSUE THREAD

**Issue by castal** [UniMath/SymmetryBook#130]
On page 2 of your introduction you refer to "Clesch and Jordan" in connection with invariant theory. But I think you mean [Alfred Clebsch](https://en.wikipedia.org/wiki/Alfred_Clebsch) (spelled with a "b") and [Paul Gordan](https://en.wikipedia.org/wiki/Paul_Gordan) (with a "G"). Gordan's wikipedia page says:

>He was known as "the king of invariant theory". His most famous result is that the ring of invariants of binary forms of fixed degree is finitely generated. He and Alfred Clebsch gave their name to Clebsch–Gordan coefficients.

**Comment by UlrikBuchholtz** [comment]
Thanks a lot, you're absolutely right! (Sorry that the introduction is still stubby—it'll probably be the last part of the book to be properly written.) Fixed in 75e3383.
