### ISSUE TITLE
typo "totally analogy"

### ISSUE THREAD

**Issue by EgbertRijke** [UniMath/SymmetryBook#131]
https://github.com/UniMath/SymmetryBook/blob/c79e8c096bd240fde3d0a28de2cfd3e3eb09be3e/group.tex#L1841

**Comment by EgbertRijke** [comment]
Do you prefer pull requests or issues for minor comments, from nonauthors?

**Comment by UlrikBuchholtz** [comment]
Thanks, I made a minimal fix in d31cf73 (@bidundas may want to rephrase?).

> Do you prefer pull requests or issues for minor comments, from nonauthors?

I'd say that either is fine, but maybe issues are the least work for all parties.
