### ISSUE TITLE
symmetry

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/SymmetryBook#15]
Move the stuff about what a symmetry is from chapter 3 to 2.

**Comment by bidundas** [comment]
Are you sure?
We discussed this, and there was an argument towards keeping chapter 2 (as) lean (as possible) containing the "necessary background" and not not the main thrust of the book.  

If you meant to say "move it to the (largely unwritten) chapter 1", I can see how that would have made sense, but the treatment there would by necessity be different.  If you go for the latter I suggest we leave what is now in chapter 3 be till we see what we manage in chapter 1.

**Comment by DanGrayson** [comment]
Here's the way I just made it look:
<img width="680" alt="Screen Shot 2019-03-22 at 3 39 14 PM" src="https://user-images.githubusercontent.com/700228/54830371-af48fb80-4cb8-11e9-8109-6fa3d76f0a34.png">
<img width="671" alt="Screen Shot 2019-03-22 at 3 39 45 PM" src="https://user-images.githubusercontent.com/700228/54830407-bc65ea80-4cb8-11e9-89fb-fc679979fbb9.png">

**Comment by DanGrayson** [comment]
I think what prompted moving the definition of the word "symmetry" was the discovery of this early use:
