### ISSUE TITLE
definitions

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/SymmetryBook#157]
Here's an example where we use a judgmental equality incorrectly.  What should we do instead?

<img width="582" alt="Screen Shot 2022-10-13 at 8 48 02 AM" src="https://user-images.githubusercontent.com/700228/195646864-adfc4c9c-8357-42c1-abfe-4f6b093c68e8.png">

**Comment by DanGrayson** [comment]
Oops, now I see that maybe ` := ` is not intended to convey something judgmental!

Maybe we should highlight the difference between the two symbols in a marginal note.

**Comment by DanGrayson** [comment]
Thanks!

**Comment by DanGrayson** [comment]
Right.  I'll add a note.

**Comment by DanGrayson** [comment]
I've added a note in commit 8cfccd1a809fea51dc6721a2f3b388514be9ee10, and I've added := to the glossary.

**Comment by marcbezem** [comment]
________________________________________
