### ISSUE TITLE
Introduce the subset notation

### ISSUE THREAD

**Issue by UlrikBuchholtz** [UniMath/SymmetryBook#174]
… in Sec. 2.20. Perhaps as an exercise stating the type of commuting triangles with last two legs being subset inclusions is a proposition.

**Comment by pierrecagne** [comment]
See commit bc6c168258769f157127d95cc7cdc0c9e4d1cd15

If this is satisfying enough, I'll close the issue.

**Comment by DanGrayson** [comment]
Looks good to me.

**Comment by marcbezem** [comment]
Why do we restrict to subsets $S_0,S_1$ of $T$, in combination with injections? The type-to-be-proved-a-proposition also depends on $i_0,i_1$. Perhaps only a typo, injection ---> inclusion, which would solve both? Or do we aim for the more general $(S_0,i_0)\subseteq(S_1,i_1)$?

**Comment by marcbezem** [comment]
Wait, I see that Ulrik above speaks of inclusions. So I will change to inclusions (fst!) and add glossary and index info. The latter is important since it is a definition of something important ($\subseteq$) inside an exercise - hard to find for the reader.
