### ISSUE TITLE
S as t+1  ??

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/SymmetryBook#19]
This notation will conflict with x+y:

<img width="515" alt="Screen Shot 2019-03-22 at 9 29 39 AM" src="https://user-images.githubusercontent.com/700228/54809971-1b117100-4c85-11e9-8c73-206f273472b8.png">

**Comment by DanGrayson** [comment]
I'm taking that out ...

**Comment by marcbezem** [comment]
No, no, we changed to right-recursive + for several reasons.

**Comment by DanGrayson** [comment]
My point is that one shouldn't provide two definitions of the same thing, not that the two things don't turn out to be the same.
