### ISSUE TITLE
function extensionality

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/SymmetryBook#20]
I'm a little dissatisfied with this discussion:

<img width="666" alt="Screen Shot 2019-03-22 at 10 33 07 AM" src="https://user-images.githubusercontent.com/700228/54813527-084f6a00-4c8e-11e9-95ce-17054889dd16.png">

because, a priori, there may be multiple functions of type `( ∏ (x:X), ( f(x) = g(x) )) → f=g`.

**Comment by marcbezem** [comment]
Yes, we discussed that and that's why you called it a principle and not an axiom.

**Comment by DanGrayson** [comment]
It might be better to move it to the section on equivalences, so we could take that function to be an inverse of the function in the exercise.

**Comment by marcbezem** [comment]
The narrative I tried to follow is: if I introduce a type former, here X->Y, I explain what it "means" that to elements of the newly formed type are equal in terms of equality of the constituent types. This "means" is often modulo an equivalence, and cannot be made precise before the definition of equivalence is in place. Cf. "equivalent" in the last sentence of 5.3.
This narrative makes sense to me, and we discussed this a couple of times. Do you really want to change that? Or only in case of function extensionality? A good solution could be to add a short section in between 2.8 and 2.9, called "Identifying functions".

**Comment by DanGrayson** [comment]
What about this way of putting it?:
<img width="657" alt="Screen Shot 2019-03-26 at 11 22 08 AM" src="https://user-images.githubusercontent.com/700228/54989723-7612d300-4fb9-11e9-9ea0-6ca64ef116e3.png">

**Comment by marcbezem** [comment]
Fine with me. But we could give a name to the function in Exc. 2.4.3 and come back to this when we have equivalences. I can make a proposal.

**Comment by marcbezem** [comment]
Done 03739c10cbdbdc4be7ddce5a2334690ad49dc8ba

The exercise had to become a definition since we cannot have an axiom depend on how somebody solves the exercise.
