### ISSUE TITLE
label display inside an equation

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/SymmetryBook#23]
... is a problem:

<img width="659" alt="Screen Shot 2019-03-25 at 9 34 29 AM" src="https://user-images.githubusercontent.com/700228/54905434-4abcb500-4ee1-11e9-9443-8b3e6ea6581d.png">

**Comment by bidundas** [comment]
sort of amusing with the "in the interest of readability" which follows.  Probably a bug in the macro allowing us to see the labels.  I suggest we live with it since these are going to vanish in any official version.
