### ISSUE TITLE
"prove"

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/SymmetryBook#32]
If the type below is not a proposition, perhaps it is not good to say that we "prove" it:

<img width="707" alt="Screen Shot 2019-05-02 at 1 14 06 PM" src="https://user-images.githubusercontent.com/700228/57097075-5bc8c500-6cdc-11e9-8b64-81057960db58.png">

**Comment by marcbezem** [comment]
Agreed ("prove" may have slipped in other places as well). What about: "The precise result is the formalized construction of a function of the following type:"

**Comment by DanGrayson** [comment]
Okay, take a look at commit d231532fdcaf70fb9f18983fda4e633a21c5a77d  .  I've also added a first paragraph to the introduction, as we need to start out by saying what the paper is about.
