### ISSUE TITLE
Lower universe levels?

### ISSUE THREAD

**Issue by marcbezem** [UniMath/SymmetryBook#34]
At several places we have defined types in higher universes than necessary. For example, the definition of Fin in 2.16.4, where the sum type is taken over Set, where it could be taken over U. As it stands, Fin is in U_2, and so are all the Fin_n. To get these in U_1 there are two options:

1. Replace \sum_{X:Set} ... by  \sum_{X:U} isSet(X) \times ... This works always, and has an analogue for \prod_{X:Set}.

2. Use Lemma 2.16.3. This only works if one has such a lemma.

I have no problem with implicitly using that X is a set if X: Fin, after a remark that we do so.
I think the extra universe level is not a good idea. In ZF Fin is a proper class, but not worse.
(Fin is not a set since if it were we would have Fin \in {Fin} \in Fin which contradicts foundation,
similarly for all Fin_n apart from Fin_0.)

I am in favor of economizing on universe levels whenever this is easy, with proper conventions to simplify terminology.

**Comment by DanGrayson** [comment]
Hmm?  We have `U : U_1` and thus `Set : U_1`, and thus `Fin : U_1`, too.

**Comment by marcbezem** [comment]
You are completely right, I don't know what I was thinking.
