### ISSUE TITLE
"more precisely"

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/SymmetryBook#35]
In this text:
<img width="756" alt="Screen Shot 2019-09-17 at 2 13 25 PM" src="https://user-images.githubusercontent.com/700228/65040768-70d58600-d955-11e9-8548-ab3606c96df3.png">
the first statement is perfectly precise, so it's not possible for something to be more precise than it.  Moreover, the second statement is a different statement, not a more precise version of the first one.

I think the second statement should be part of the proof, not part of the statement.

**Comment by marcbezem** [comment]
I think something like "t is a member of T$ is more precise than "T has a member", even if T is a proposition. But I have no problem to follow your suggestion. More precisely :-), no other problem than lack of time, will do this evening!

**Comment by marcbezem** [comment]
Done. Pls pull and take a look.

**Comment by DanGrayson** [comment]
Thanks!
