### ISSUE TITLE
Should these be sans serif, roman or italic?

### ISSUE THREAD

**Issue by marcbezem** [UniMath/SymmetryBook#38]
With Pierre we work on making the notations more systematic. The current proposal is as below,
followed by some examples. Please let us know what you think.

% Should these be sans serif, roman or italic?
% Rule (under discussion): constructors italic, defined elements roman, typeformers sf

\newcommand{\constructor}[1]{\mathit{#1}}
\newcommand{\function}[1]{\mathrm{#1}}
\newcommand{\typeformer}[1]{\mathsf{#1}}

% Typeformers

\newcommand{\bool}{\typeformer{Bool}}

% Constructors

\newcommand{\yes}{\constructor{yes}}
\newcommand{\no}{\constructor{no}}

% Functions and defined elements

\newcommand{\id}{\mathord{\function{id}}}
\newcommand{\pt}{\function{pt}}

**Comment by UlrikBuchholtz** [comment]
I'm against bringing in sans-serif as yet another shape. I think we should be able to make do with (combinations of) regular/bold and roman/italic. (With the occasional use of calligraphic letters, e.g., for universes.)

As a general rule, I like constants to be roman and variables to be italic, but I'm open to negotiations. (According to this rule, italics may be underused, particularly for multiletter words.)

Why do we need to distinguish constructors from other defined constants?

I think bold may be reasonable for type formers, especially when the same name is also in use for a term former, e.g., (regular) 1 : \NN and (bold) 1 : \UU.

For consistency, we could then make all type formers bold, also Set, Gpd, etc., even though these aren't used for term formers as well. Another option is to simply distinguish the term and type formers via lower- and uppercase initial letters when possible. (I slightly prefer the latter.)
