### ISSUE TITLE
tikz distortion

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/SymmetryBook#46]
The diagrams made with tikz have ugly artifacts in them:

<img width="853" alt="Screen Shot 2020-03-26 at 11 45 15 AM" src="https://user-images.githubusercontent.com/700228/77672837-6117a980-6f57-11ea-8748-a77546827e0f.png">

**Comment by pierrecagne** [comment]
Could you give the section you found that in ? I find sometimes that it varies from pdf-viewer to pdf-viewer.

**Comment by DanGrayson** [comment]
It's a bit after 2.11.6.

**Comment by DanGrayson** [comment]
Acrobat Reader gives a similar display:

<img width="830" alt="Screen Shot 2020-03-26 at 12 55 17 PM" src="https://user-images.githubusercontent.com/700228/77679830-1a2eb180-6f61-11ea-871f-4f45704eb071.png">

The previous screenshot is from Mac OS X "Preview".

**Comment by UlrikBuchholtz** [comment]
This should now be fixed (with other improvements to TikZ-cd arrows) in commit 1a91785
