### ISSUE TITLE
autocite

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/SymmetryBook#49]
Replacing \cite by \autocite had a bad effect here:

<img width="493" alt="Screen Shot 2020-03-28 at 5 34 55 PM" src="https://user-images.githubusercontent.com/700228/77835438-8accfe00-711a-11ea-8630-75640d0177c9.png">

@UlrikBuchholtz

**Comment by UlrikBuchholtz** [comment]
Fixed in d19a8f8 by making ```\cite``` give an error encouraging us to use ```\footcite``` instead (and changing the few ```\cite``` instances we had.)
