### ISSUE TITLE
group.tex commented out code

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/SymmetryBook#57]
There is a gigantic section of group.tex that is commented out and appears to be duplicated in subgroup.tex.  Can I delete it?

**Comment by pierrecagne** [comment]
Ping @bidundas to be sure but I think you can. The idea was to make an entire chapter about subgroups instead of a section in the group chapter.

**Comment by bidundas** [comment]
As said, I was planning a rewrite of the subgroup chapter, but it was not on my priority-list pending proofreading and approval from Marc.  If someone else feels the urge to do this rewriting now, he can delete anything he wants.

Bjorn

**Comment by DanGrayson** [comment]
The question wasn't about rewriting anything, just about removing 829 lines of commented-out text.  It won't affect the book.

**Comment by marcbezem** [comment]
I'm fine with removing those 829 lines, please make an easy-to-identify commit "remove old stuff about monomorphisms and subgroups". For the new section on subgroups, see my comments in #51 .

**Comment by DanGrayson** [comment]
done in commit dafcb0a3d8b2e1e7d2bc04255c2d61ab35118159
