### ISSUE TITLE
glossary of symbols

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/SymmetryBook#64]
We could use the package at https://ctan.org/pkg/glossaries to generate an index of symbols, so readers can find the definitions.  Here is how it looks in another paper I'm working on:

<img width="475" alt="Screen Shot 2020-04-18 at 9 13 03 AM" src="https://user-images.githubusercontent.com/700228/79640032-f3752c80-8154-11ea-93d2-8e9ef5083730.png">

**Comment by UlrikBuchholtz** [comment]
Memoir already includes some basic glossary support (cf. sec. 17.3 of the memoir manual). If we don't need anything fancy, that should suffice, otherwise there's also the `glossaries-extra` package (from the authors of `glossaries.sty`) with more bells and whistles.

**Comment by UlrikBuchholtz** [comment]
I've now implemented a glossary and added some stuff (using Memoir's features). Add an entry using ```\glossary(sort){key}{desc}``` where `sort` is an optional `makeindex` sort string, `key` is the thing to define (whose macros may need ```\protect```ion), and `desc` is the description.

@DanGrayson in your screenshot there are no descriptions, so it's essentially another index. An index has the benefit that multiple citations (to different pages) can be issued, but a glossary has the benefit that the descriptions are right there, and the same symbol can appear twice with different descriptions. I've used that feature for ```\mkgroup``` and ```\mkhom```.

Do we want to keep this glossary-style setup or rather have an index-style symbol index?

**Comment by UlrikBuchholtz** [comment]
Now that we've decided to keep the glossary as is, we need a guide on how to make (makeindex) sort-keys for symbols so that similar symbols occur next to each other. (E.g. binary relations, various arrows, superscripts, bar/tilde, etc., then numerals, then alphabetical symbols.)

**Comment by DanGrayson** [comment]
I'll take a stab at that .

**Comment by DanGrayson** [comment]
I've done it, but I'll hold off pushing it until after Friday, for Bjorn's sake.

**Comment by bidundas** [comment]
Brilliant. Won't start editing for another hour, so feel free to push

Bjorn

**Comment by bidundas** [comment]
Ok, I’m mostly done for today.  Fell free to go wild.  

I had a minor catastrophe with preview and lost all my proof marks for chapter 2 and 4, so I have to go through everything and reconstruct them before I can do anything about the ones I didn’t have in my RAM.  However, before I get that far I’ll edit chapter 5 (where luckily most of my copy editing was on a paper copy Marc had donated to me).

Bjorn

**Comment by DanGrayson** [comment]
I find the Mac OS X Preview program is super buggy, but I like the annotation features, sigh.

I've updated the glossary -- take a look.

**Comment by UlrikBuchholtz** [comment]
Looks good!

**Comment by bidundas** [comment]
Looks good.  Thanks

I’ll mostly edit the subgroup chapter today, so group.tex is open for others.

Bjorn
