### ISSUE TITLE
introduction to 4.3

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/SymmetryBook#68]
... should talk about maps on loops and how they preserve operations

<img width="631" alt="Screen Shot 2020-04-27 at 9 24 28 AM" src="https://user-images.githubusercontent.com/700228/80383220-eea52c80-8868-11ea-851b-ebf15beefd15.png">

**Comment by UlrikBuchholtz** [comment]
This issue should eventually result in a re-working of most of section 4.3 (sec:homomorphisms).

For now, I've added (in 9789b0b) the construction that taking loops is compatible with composition, thus enabling a smoother treatment of lem:Znatural (was 4.3.9, now 4.3.11).

One small issue is the naming of homormorphisms: If we have groups G, H, etc. around,
then after a homormorphism f, it's annoying to call the next one g, since it clashes with group elements. How about we use greek letter phi, psi, etc. for homomorphisms instead?

Over to you, @DanGrayson .

**Comment by DanGrayson** [comment]
Another idea would be to use f, f', f'', for homomorphisms.  Then we won't run out of letters.

**Comment by DanGrayson** [comment]
Ulrik, wouldn't these proofs be simpler if done by path induction on the paths equating the base point to the image of the other base point?

<img width="585" alt="Screen Shot 2020-05-01 at 2 30 25 PM" src="https://user-images.githubusercontent.com/700228/80835469-79af5b00-8bb8-11ea-91ce-2c139f6b76e1.png">
<img width="881" alt="Screen Shot 2020-05-01 at 2 27 09 PM" src="https://user-images.githubusercontent.com/700228/80835472-7ae08800-8bb8-11ea-9587-b7a3bd5abc74.png">

**Comment by DanGrayson** [comment]
I've added some motivation at the start of 4.3:

<img width="599" alt="Screen Shot 2020-05-01 at 4 53 01 PM" src="https://user-images.githubusercontent.com/700228/80844480-4080e600-8bcc-11ea-87c6-9691a599bcd6.png">

**Comment by bidundas** [comment]
that seems to work, thanks

Bjorn

**Comment by marcbezem** [comment]
Very good choice to explain the motivation in the case of the reflexivity path!

**Comment by DanGrayson** [comment]
Okay, I'll simplify those proofs and add definitions (in 4.3) of composition and identity for group homomorphisms. And maybe separate the definition of isomorphism.

**Comment by DanGrayson** [comment]
One construction simplified:
<img width="598" alt="Screen Shot 2020-05-05 at 3 00 04 PM" src="https://user-images.githubusercontent.com/700228/81110455-2e12ef00-8ee1-11ea-96b8-5cd9bd1316dc.png">

**Comment by UlrikBuchholtz** [comment]
That looks fine. One remark about this Definition-Construction pairing, though: I would prefer to keep “Definition” environments for definitions that are completed when the environment is over. Perhaps we could add a new environment “Problem” that would be set in italics like lemmas, but be justified with a “Construction” rather than a “Proof”?

If we call it “Problem” (following (translators of) Euclid), the grammar should probably change, so that, e.g. for 4.3.10 above, we say “we want” instead of “we get”.

**Comment by DanGrayson** [comment]
Yes, that left me unsettled, too.  And "Problem"/"Construction" is just what VV recommended to us.  I wonder whether there is a better pair of words, though, since the word "Problem" doesn't convey the sense that the solution was ever found.

**Comment by UlrikBuchholtz** [comment]
What about “[Constructure](https://en.wiktionary.org/wiki/constructure)”: That which is constructed or formed?
Other optons: fact, factum, product.

**Comment by DanGrayson** [comment]
What about "Definiendum"/"Definition"? See
https://www.dictionary.com/browse/definiendum

**Comment by UlrikBuchholtz** [comment]
Maybe, but “definiendum” usually goes with “definiens”, and has the
connotation of a dictionary entry.

**Comment by DanGrayson** [comment]
That pair sounds even better.  And notice that "Definiendum" sort of rhymes with "Theorem".

**Comment by DanGrayson** [comment]
On the other hand, no one's going to appreciate having to acquire two more Latin words.

**Comment by bidundas** [comment]
beware of alienating the readers

Bjorn

**Comment by marcbezem** [comment]
What about Goal/Solution? Goes with "we want" and not with "we get".
I also considered Goal/Means, but didn't like Means.

**Comment by DanGrayson** [comment]
Or what about Goal/Construction?

**Comment by UlrikBuchholtz** [comment]
I like Goal/Construction too! And I like that the grammar changes a bit, so the writing is varied, and “goal” is much better than “problem”, since the latter belongs on a problem sheet, or maybe under “open problems”. (Do people talk about “closed problems” for anything that wasn't, at one time, “open”?)

**Comment by DanGrayson** [comment]
Yes, I have the same feeling.  "Problem" sounds like something on a bug report to a software company.

**Comment by marcbezem** [comment]
Goal/Construction is also fine with me. The phrase "construction" gets a little stretched when strong principles are involved.

**Comment by UlrikBuchholtz** [comment]
I've added a goal and a construction environment to test things out. One potential problem is in references: We get things like “Another application of Goal 2.19.4 is …”, where “goal” doesn't sound quite right. (“Problem” would likewise sound wrong.).
Here's a radical idea: Use “construction” for both! The typography distinguishes the construction as goal/constructure/constructee/construendum/definiendum/… (small caps) from construction as means/constructor/construens/definiens/… (italics). What do you think?

**Comment by DanGrayson** [comment]
But it's a good thing that “Another application of Goal 2.19.4 is …” doesn't sound right, because we should say “Another application of Construction 2.19.5 is …” instead.

**Comment by UlrikBuchholtz** [comment]
In the latests commits, I've implemented the environments ```construction``` and ```implementation```, see 2.19.4 for an example.

**Comment by DanGrayson** [comment]
I think it looks great!!

**Comment by bidundas** [comment]
Like it too. Thanks.  I’d be even more euphoric were there parentheses around n\leq m.

Is this setup stable so that I can implement it elsewhere?

Bjorn

**Comment by UlrikBuchholtz** [comment]
> Is this setup stable so that I can implement it elsewhere?


Knock yourself out! Beware that “implementation” is a bit brittle, in that
the number is simply the current value of the subsection counter, so if you
have, e.g., a remark in between a construction and its implementation,
you’ll need to explicitly write

\begin{proof}[Implementation of \cref{label}]
…

Maybe it’d be better to simply require a label argument in the
implementation environment?

**Comment by DanGrayson** [comment]
Yes, make  it a requirement.  That's easier than checking for cases where we omitted it and it pointed to the wrong thing, since that's an onerous task.

**Comment by UlrikBuchholtz** [comment]
Makes sense: It's now a requirement. (Bjorn, I changed a line in subgroup.tex)
