### ISSUE TITLE
arrow notation for composition

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/SymmetryBook#69]
Add to the introduction something about using this sort of notation to *define* a composite function:

<img width="320" alt="Screen Shot 2020-04-27 at 10 14 03 AM" src="https://user-images.githubusercontent.com/700228/80388804-f1575000-886f-11ea-9968-7891ced21f3d.png">

**Comment by DanGrayson** [comment]
It looks like this now:
<img width="424" alt="Screen Shot 2020-04-27 at 3 04 27 PM" src="https://user-images.githubusercontent.com/700228/80415634-6cccf780-8898-11ea-9b65-693ecd208f58.png">

**Comment by bidundas** [comment]
Splendid (though the majority decision seemed to be to change the name of f^\abstr to \USym f: I can take care of that for the entire book)

Bjorn
