### ISSUE TITLE
variables as words

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/SymmetryBook#7]
We should avoid using variables as English words, as they can't be read.  Here is an example:
<img width="928" alt="screen shot 2019-02-27 at 2 46 17 pm" src="https://user-images.githubusercontent.com/700228/53494667-8c9f3a80-3a9e-11e9-996d-2483f27e4045.png">

Better than "on an A" would be "on an element of A".

**Comment by UlrikBuchholtz** [comment]
Agreed. Fixed in commit 9114fe151e605f3e2beca6e7cd5ec9c475f1fec1
