### ISSUE TITLE
comments on 6.3 Heaps

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/SymmetryBook#71]
@UlrikBuchholtz 

In
<img width="576" alt="Screen Shot 2020-05-07 at 8 41 43 AM" src="https://user-images.githubusercontent.com/700228/81301434-a6db8d80-903e-11ea-8fd7-f1176dfa2ed4.png">
does "different" have a meaning?  "Not judgmentally equal"?

Moving it to chapter 4, as you suggest, might be good.  The exercises are good ones!

It might be good to expand that footnote by telling what motivated Sushkevich to define the concept.

<img width="18" alt="Screen Shot 2020-05-07 at 8 43 57 AM" src="https://user-images.githubusercontent.com/700228/81301645-ef934680-903e-11ea-918e-54fc085d945d.png">

In

<img width="584" alt="Screen Shot 2020-05-07 at 8 44 36 AM" src="https://user-images.githubusercontent.com/700228/81301700-0174e980-903f-11ea-842f-c3d3da48e009.png">
it would be better to say something like "the symmetry groups of the two endpoints are merely isomorphic."

Perhaps add something to this:

<img width="593" alt="Screen Shot 2020-05-07 at 8 45 40 AM" src="https://user-images.githubusercontent.com/700228/81301956-5add1880-903f-11ea-97ab-8689e2aa8f7f.png">
such as ", as envisioned by the following exercise", so the reader isn't left hanging.

**Comment by UlrikBuchholtz** [comment]
Thanks!

> does "different" have a meaning? "Not judgmentally equal"?

“might be different” means ”not necessarily judgmentally equal”.

**Comment by DanGrayson** [comment]
One may consider `a` and `a'` to be variables in that sentence, in which case they are definitely not judgmentally equal.

**Comment by UlrikBuchholtz** [comment]
I still want to emphasize the contrast to loop types. See the current version:
![heaps-vs-loops](https://user-images.githubusercontent.com/471776/81385115-158a1b00-9113-11ea-9f6f-44d2193032ea.png)

**Comment by bidundas** [comment]
I think it is good to emphasize this point, even if we’re not allowed to say ”different”.   The current version is good by me (as were some of the previous ones) 

Bjorn

**Comment by DanGrayson** [comment]
I like the rephrasing a lot.
