### ISSUE TITLE
Def. 2.18.10 ff.

### ISSUE THREAD

**Issue by marcbezem** [UniMath/SymmetryBook#74]
I would like to add a syntactic definition of [a] as (R(a),|(a,refl_R(a))|). Of course we keep the terminology  "the equivalence class containing a". 

It would be good to recall the convention that we may coerce [a] to R(a), which is what we do, e.g., in the proof of Lem. 2.18.11, where we write P ≡ [b]. Without coercing this could be wrong!

**Comment by UlrikBuchholtz** [comment]
Sounds good to me!

**Comment by marcbezem** [comment]
BTW I like this subsection on set-quotients.

**Comment by marcbezem** [comment]
See the commit with xca:all-prop-image + some minor changes/modifications of 2.18

**Comment by DanGrayson** [comment]
That was commit bd0cd8bf

So, Marc, is this done?

**Comment by marcbezem** [comment]
Yes, done in footnote 60.
