### ISSUE TITLE
definition of covering

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/SymmetryBook#8]
Instead of this:
<img width="693" alt="screen shot 2019-02-27 at 2 54 12 pm" src="https://user-images.githubusercontent.com/700228/53495133-96756d80-3a9f-11e9-9353-5e2b22f1d602.png">
it would be better to define what a *covering of B* is.  It's a type A, a map f:A->B, etc.

**Comment by bidundas** [comment]
Do you find the current version to your liking?

**Comment by DanGrayson** [comment]
I think the universal covering should be simply connected, not contractible.

The word "covering" survives in a few places.

I'm not sure "set map" is optimal yet, since it's hard to guess the meaning -- it's an improvement over "covering".  If we were using "family of sets", then at least there would be a difference between a "connected family of sets" and a "family of connected sets".  I wonder if there are ways to decorate "family" so it could be used for both concepts: maps to B, and maps from B to a universe.  A "displayed family of sets over B"?

**Comment by DanGrayson** [comment]
At one point we were considering using "set bundle".  I like that better than "set map".

**Comment by bidundas** [comment]
You are right regarding "set bundle" and the macro will be changed.
The surviving "coverings" are hopefully in "Groups" and will be corrected when I move through the file.
