### ISSUE TITLE
LEM

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/SymmetryBook#80]
We're referring already to LEM without stating or discussing it.  That might be done in 2.12 (Propositions, etc.).

**Comment by UlrikBuchholtz** [comment]
I'm going to do this shortly as part of the subtype/injections reorganization.

**Comment by pierrecagne** [comment]
I wrote a paragraph or two last week. Let me format it correctly and push it then.

**Comment by UlrikBuchholtz** [comment]
OK, great.

**Comment by pierrecagne** [comment]
I made a mistake I think when pushing. That is weird I was up-to-date to master then I commited my changes and pushed to master but a lot of old commits appear now on the commit page...

**Comment by pierrecagne** [comment]
Nevermind, my github interface did not react properly, everything seems to be fine now.

**Comment by UlrikBuchholtz** [comment]
Thanks. This is now in Sec. 2.13 together with some additions of mine. (94e489e)
