### ISSUE TITLE
Klein and Lie -- ∞ - groups ?

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/SymmetryBook#86]
Were Klein and Lie interested in ∞ - groups?

<img width="696" alt="Screen Shot 2020-07-17 at 1 31 18 PM" src="https://user-images.githubusercontent.com/700228/87814578-9b1ffa80-c829-11ea-904a-b81c413ec5a2.png">

**Comment by bidundas** [comment]
In the sense that they were interested in topological groups that weren’t necessarily discrete. 

Bjorn

**Comment by DanGrayson** [comment]
Ah, right.

**Comment by UlrikBuchholtz** [comment]
Isn't it more subtle, though: There's a leap from looking at 1-groups with topological (or smooth or algebro-geometric) structure, to looking at the presented discrete infinity-groups. (And a further leap to consider structured infinity-groups.

**Comment by UlrikBuchholtz** [comment]
> Are you trying to say that the study of Lie groups is not pursued well by consideration of identity types in type theory?

No, I didn't say that, nor was I trying to. I was just pointing out that there's a difference between looking at Lie groups as 1-groups with smooth structure versus the corresponding discrete infinity-groups. To study the latter via identity types, you need the shape functor to turn smooth/continuous paths into identifications.

(As it happens, I think there is much promise in studying (higher) Lie groups via cohesive type theory.)

**Comment by UlrikBuchholtz** [comment]
I'll try to rephrase the sentence to indicate that Lie was interested in continuous groups, and Klein in discontinuous groups.

**Comment by UlrikBuchholtz** [comment]
Here's an attempt (in 61ae220)
![issue86](https://user-images.githubusercontent.com/471776/88041167-4b537300-cb4a-11ea-889d-1eabcacfde35.jpg)

**Comment by DanGrayson** [comment]
Sounds good to me.

Change "groups gives" to "groups give".

**Comment by bidundas** [comment]
I agree with what you’ve written, Ulrik.  

It’s a good point, though not the one I wanted to make (which I offer here solely for the sake of the record - I do not advocate that we follow up this thought).  
The smooth structure is ‘more structure’, 
but if we’re less greedy and follow the ‘types as spaces’ slogan (which we may not subscribe to) the analog of a topological group would in our world best be captured by ‘less structure’: 
a (pointed, connected) type 
(as opposed to 1-type).

Bjorn

**Comment by DanGrayson** [comment]
It seems to me the marginal note addresses that idea.

**Comment by UlrikBuchholtz** [comment]
Thanks for spotting the typo, Dan.

Regarding more and less structure: Since we have a span Disc1Group ← Lie1Group → Disc∞Group, and not a single map, between the extremes here, there's both the addition and then removal of structure when going from the underlying discrete 1-group of a Lie group to its ∞-group.

I think this is more or less clear from what's written now (if you know what to look for), but feel free to reword.

**Comment by marcbezem** [comment]
Perhaps add in the footnote, to "identifications",  "_of loops_".

**Comment by DanGrayson** [comment]
I think what's intended there is identifications of pairs of points.

**Comment by marcbezem** [comment]
I didn't get that. Where is the aspect of non-trivial higher identifications of an ∞-group?

**Comment by marcbezem** [comment]
I did perhaps (mis)read "parametrized by real intervals". What does this mean? I read this as a family of loops depending on a real number ranging over [0,1].

**Comment by bidundas** [comment]
That I cannot see.

**Comment by bidundas** [comment]
Don’t understand this either.  How is the inclusion of (pointed connected) 1-types into (pointed connected) types not a single map?  
I aknowledge that one may have more advanced and complicated ideas in one’s head, but this is the naive and simple one I originally put forward (note that I don’t anymore - However, if the point induces controversy beyond the little noice I make, I suggest we abandon mention of Klein and Lie at this point).

Bjorn

**Comment by UlrikBuchholtz** [comment]
> Don’t understand this either. How is the inclusion of (pointed connected) 1-types into (pointed connected) types not a single map?

That is clearly a single map, but it doesn't capture the process I thought you meant, which was: first we add topological or smooth structure, and then we look at the presented homotopy type.

In cohesion, we don't explicitly add this structure, as it's there all along, but there are still two maps from 1-groups to infinity-groups: The inclusion you mention and the shape. We only get non-trivial infinity-groups by applying the latter.

**Comment by bidundas** [comment]
The things we say are not contradictory (we actually agree - or, at least, I agree with you).  I originally intended to say just the simple thing and not comment on the deeper story.

Bjorn

**Comment by marcbezem** [comment]
The new text is better for me, because it refers to higher loops. Bear with me a bit more, among the authors I'm probably closest to the intended readers by not knowing enough mathematics. In view of footnote 44, do I understand correctly we have continuous (or smooth) functions [0,1] -> A leading to (smooth) paths ("identifications") in the homotopy type of A? Analogously for "into identifications of loops"? And in both cases we leave out "in the homotopy type", since this is in the ref to footnote 44 and 45, and would anyway lead us too far.

**Comment by UlrikBuchholtz** [comment]
>  In view of footnote 44, do I understand correctly we have continuous (or smooth) functions [0,1] -> A leading to (smooth) paths ("identifications") in the homotopy type of A? Analogously for "into identifications of loops"? And in both cases we leave out "in the homotopy type", since this is in the ref to footnote 44 and 45, and would anyway lead us too far.

Yes, that's right. Do you think it's clearer if we explicitly refer to the homotopy type construction in footnote 3, ch. 4?

BTW, someone(!) should make a start on Sec. 5.7. I don't know what “early” is supposed to mean, though: Is this supposed to connect up to whenever people starting thinking about infinity-groups? This is of course a gradual thing, presumably beginning with a topological viewpoint (of up-to-homotopy structure) for a long time before Waldhausen's (dystopian?) remark about “brave new algebra” (although that was more about higher rings), to things like higher gauge theory, and connected with both loop space recognition theorems and the homotopy hypothesis, and all of this with early precursors for 2-groups.

**Comment by DanGrayson** [comment]
5.7 is entitled "historical remarks" and 5 is entitled "subgroups", so is 5.7 supposed to be about the history of subgroups?

**Comment by bidundas** [comment]
This is just a place holder for an intention that chapters should contain historical information.  As I wrote things it got longer and had to be split in several chapters, and this is where this place holder by accident ended up (actually, it’s strange that it’s not in the finite groups chapter).  Whether it was a good idea to start with is another question.  I suspect nobody has the energy to do anything about such matters in the foreseeable future.  Our options are 1. abandon the idea and delete the heading, 2. keep the idea and the heading until we get around to anything about it.

Bjorn

**Comment by marcbezem** [comment]
@UlrikBuchholtz "Yes, that's right. Do you think it's clearer if we explicitly refer to the homotopy type construction in footnote 3, ch. 4?"

No, I think that would lead us to far. I'm more in favour of an example. It seems that the only example that is readily available at this point in the book is S1=S1, after Exercises 3.7.5,6. That would make for a 1-group.

**Comment by marcbezem** [comment]
What is the status of the connected component of U_0 in U_1 as a classifying type? Is that a good example of an ∞-group?
How "infinite" is it? (Could depend on what HITs we postulate in U_0, for example, suspensions.)

**Comment by UlrikBuchholtz** [comment]
> @bidundas This is just a place holder for an intention that chapters should contain historical information. As I wrote things it got longer and had to be split in several chapters, and this is where this place holder by accident ended up (actually, it’s strange that it’s not in the finite groups chapter). Whether it was a good idea to start with is another question. I suspect nobody has the energy to do anything about such matters in the foreseeable future. Our options are 1. abandon the idea and delete the heading, 2. keep the idea and the heading until we get around to anything about it. Bjorn

I think we should keep it, but I've moved it to an appendix for now. I think this may ultimately be the right place, because it'll mention the impetuses coming from geometry and algebra, which will be covered after the subgroup chapter anyway.

> @marcbezem No, I think that would lead us to far. I'm more in favour of an example. It seems that the only example that is readily available at this point in the book is S1=S1, after Exercises 3.7.5 and 6. That would make for a 1-group. I can add this if we agree that it is worthwhile. It would make these exercises more relevant.

I think you mean “2-group”: Aut_U(S1) is indeed a nice example of a 2-group (along with AUT(G) = Aut_U(BG_) for any 1-group G), but not of a Lie group. (These we can treat after some geometry.)

> @marcbezem What is the status of the connected component of U_0 in U_1 as a classifying type? Is that a good example of an ∞-group?
> How "infinite" is it? (Could depend on what HITs we postulate in U_0, for example, suspensions.)

It depends more on LEM: With LEM, you can make an element that swaps empty types and contractible types. In general, you can permute types with equivalent automorphism infinity-groups, but I don't know other such coincidences.

Without LEM, it might well be that this group is trivial, for instance via a parametricity interpretation.

**Comment by UlrikBuchholtz** [comment]
I think we're done with this, the remaining part about examples has been raised in issue #90.
