### ISSUE TITLE
Definition of type of pointed connected groupoids

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/SymmetryBook#87]
Why not simplify things and just incorporate being a groupoid directly into the definition of the type of pointed connected groupoids?   In other words, let the symbols correspond to the words.

<img width="685" alt="Screen Shot 2020-07-17 at 1 45 37 PM" src="https://user-images.githubusercontent.com/700228/87815794-dd4a3b80-c82b-11ea-90fe-b3f93380cc44.png">

**Comment by UlrikBuchholtz** [comment]
I think the idea was that the type displayed is in some sense simpler, but I would also prefer having the definition match the words, with the exercise then introducing the “simpler”, equivalent type.

**Comment by DanGrayson** [comment]
I'll change it that way.

**Comment by DanGrayson** [comment]
Done in commit 8dc6cc2da645efb8d567d43ef8d68d448dd0a504

<img width="1077" alt="Screen Shot 2020-07-18 at 12 40 51 PM" src="https://user-images.githubusercontent.com/700228/87860550-1229c180-c904-11ea-86bf-c16ce01fdc62.png">


<img width="710" alt="Screen Shot 2020-07-18 at 12 41 37 PM" src="https://user-images.githubusercontent.com/700228/87860554-16ee7580-c904-11ea-99af-7b6d39860d08.png">

**Comment by marcbezem** [comment]
I have argued in the past for the current definition, but could not convince some others. I had added the "reconciliating exercise". So I'm happy, but perhaps somebody else is not.
I see you leave out parentheses in isGrpd A and isConn A. Many (all?) similar places we do use parentheses.

**Comment by DanGrayson** [comment]
Thanks, I've added parentheses in commit 62134625fa79b5067e4ec65f1c5b0634c0757a5d

<img width="600" alt="Screen Shot 2020-07-19 at 4 38 59 PM" src="https://user-images.githubusercontent.com/700228/87884724-08708e80-c9d6-11ea-8c56-6511f2765f02.png">
