### ISSUE TITLE
Rendering

### ISSUE THREAD

**Issue by LevT2** [UniMath/SymmetryBook#93]
Please help with 
https://www.xm1math.net/texmaker/doc.html

or suggest another tool and its right settings, 
preferably for Windows or online

**Comment by marcbezem** [comment]
Many of us use Mac, some use Linux. I have the installed the symmetry book on both, with more or less standard installation of latex. This complies with ````https://www.latex-project.org/get/

**Comment by DanGrayson** [comment]
I have a Windows machine here, and could try to do it here if the various distributions at page Marc linked to don't work.

**Comment by LevT2** [comment]
> I have a Windows machine here, and could try to do it here if the various distributions at page Marc linked to don't work.

Okay, I am personally able to work this issue out with some kind of hypervisor.
But please give it a try with texmaker or any other really cross-platform app.

I'd prefer any even more tinier viewer. 
There is little sense in installing a full-fledged tex system just to render a book.

**Comment by marcbezem** [comment]
Would it help to just send you pdf or dvi?

**Comment by LevT2** [comment]
> Would it help to just send you pdf or dvi?

Thank you, surely
pdf

**Comment by marcbezem** [comment]
Here it is: [book.pdf](https://github.com/UniMath/SymmetryBook/files/5278655/book.pdf)

**Comment by UlrikBuchholtz** [comment]
We should probably say that we're still working on the book, and when we have a more complete draft, then we can consider making a pdf available directly from the repository, or an associated gh-page.

**Comment by DanGrayson** [comment]
Good idea.

We probable don't want the pdf file to be a file in the repository itself, for then we'd be keeping gazillions of old
copies of that big file around.
